# Generated by Django 2.0.6 on 2018-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacebookBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_known',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
