# Generated by Django 2.0.6 on 2018-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacebookBackend', '0003_auto_20180701_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentlinks',
            name='file',
            field=models.FileField(max_length=256, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_ids',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='coverpicture',
            name='image',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friends_ids',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='captions',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_ids',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tagged_ids',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='born_place',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_known',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reply',
            name='like_ids',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_ids',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
